// Client-side export helpers used by the Share menu in the HTML viewer.
// Four of the five formats run entirely in the browser:
//   - PDF  : open the artifact in a popup window and trigger window.print().
//            The user picks "Save as PDF" from the system print dialog.
//   - HTML : download the artifact as a single .html file via a Blob URL.
//   - ZIP  : pack the artifact into a stored-mode ZIP (see ./zip.ts).
//   - PNG  : render the artifact in an off-screen iframe and capture it via
//            html2canvas. Useful for posters, social posts, business cards
//            — anywhere the deliverable is a flat raster image.
// PPTX export is fundamentally different — it asks the agent to convert the
// artifact server-side, so it lives in ProjectView.tsx (not here).

import { buildSrcdoc } from './srcdoc';
import { buildZip } from './zip';

function safeFilename(name: string, fallback: string): string {
  const slug = (name || fallback)
    .replace(/[^\w.\-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return slug || fallback;
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke later — Safari sometimes hasn't finished reading the blob yet
  // when the click handler returns.
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

export function exportAsHtml(html: string, title: string): void {
  const doc = buildSrcdoc(html);
  const blob = new Blob([doc], { type: 'text/html;charset=utf-8' });
  triggerDownload(blob, `${safeFilename(title, 'artifact')}.html`);
}

export function exportAsZip(html: string, title: string): void {
  const doc = buildSrcdoc(html);
  const slug = safeFilename(title, 'artifact');
  const blob = buildZip([
    { path: `${slug}/index.html`, content: doc },
    {
      path: `${slug}/README.md`,
      content: `# ${title || slug}\n\nGenerated by Open Design.\nOpen index.html in a browser to view.\n`,
    },
  ]);
  triggerDownload(blob, `${slug}.zip`);
}

// Open the artifact in a new tab via a Blob URL with a self-printing
// script injected. Going through a Blob URL (rather than `window.open('')`
// + `document.write`) avoids two failure modes we hit before:
//   - `noopener` makes `window.open` return null, leaving an empty popup
//     and triggering a duplicate fallback tab.
//   - Cross-document writes are flaky in some browsers and don't always
//     fire load events the way an inline script tied to the document does.
// The injected script also sets the document title so "Save as PDF" picks
// a sensible default filename.
//
// `deck: true` injects an extra print stylesheet that lays every `.slide`
// section out one-per-page top-to-bottom. The deck framework already ships
// equivalent print rules; this is a safety net for older / partially
// regenerated decks where the framework was stripped — without it,
// horizontal-snap decks print only the visible slide.
export function exportAsPdf(
  html: string,
  title: string,
  opts?: { deck?: boolean },
): void {
  let doc = buildSrcdoc(html);
  if (opts?.deck) doc = injectDeckPrintStylesheet(doc);
  doc = injectPrintScript(doc, title);
  const blob = new Blob([doc], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (!win) {
    // Popup blocked — at least the tab navigation may have happened above.
    // Nothing else we can do without a fresh user gesture.
  }
  // Revoke later — the loaded document keeps a reference until the tab
  // closes; revoking the URL string only removes the lookup name.
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function injectPrintScript(doc: string, title: string): string {
  const safeTitle = JSON.stringify(title || 'artifact');
  // setTimeout gives stylesheets and images one tick to settle before the
  // print dialog measures the page; without it some print previews come
  // out blank in Chrome.
  const script = `<script>try{document.title=${safeTitle}}catch(e){}window.addEventListener('load',function(){setTimeout(function(){try{window.focus();window.print()}catch(e){}},300)})</script>`;
  if (/<\/head>/i.test(doc)) return doc.replace(/<\/head>/i, `${script}</head>`);
  if (/<\/body>/i.test(doc)) return doc.replace(/<\/body>/i, `${script}</body>`);
  return doc + script;
}

// Stitches every .slide into a vertical multi-page PDF: 1920×1080 per page,
// no margins, scroll-snap and horizontal flex disabled. `!important` guards
// override skill-specific styles that pin the deck to `display: flex` /
// `overflow: hidden` for on-screen swiping.
const DECK_PRINT_CSS = `
@media print {
  @page { size: 1920px 1080px; margin: 0; }
  html, body {
    width: 1920px !important;
    height: auto !important;
    overflow: visible !important;
    background: #fff !important;
  }
  body {
    display: block !important;
    scroll-snap-type: none !important;
    transform: none !important;
  }
  .slide, [data-screen-label], section.slide, .deck-slide, .ppt-slide {
    flex: none !important;
    width: 1920px !important;
    height: 1080px !important;
    min-height: 1080px !important;
    max-height: 1080px !important;
    page-break-after: always;
    break-after: page;
    scroll-snap-align: none !important;
    transform: none !important;
    position: relative !important;
    overflow: hidden !important;
  }
  .slide:last-child, [data-screen-label]:last-child { page-break-after: auto; break-after: auto; }
  .deck-counter, .deck-hint, .deck-nav,
  [aria-label="Previous slide"], [aria-label="Next slide"] {
    display: none !important;
  }
}
`;

function injectDeckPrintStylesheet(doc: string): string {
  const tag = `<style data-deck-print="injected">${DECK_PRINT_CSS}</style>`;
  if (/<\/head>/i.test(doc)) return doc.replace(/<\/head>/i, `${tag}</head>`);
  if (/<head[^>]*>/i.test(doc)) return doc.replace(/<head[^>]*>/i, (m) => `${m}${tag}`);
  return tag + doc;
}

// Render the artifact in a temporary off-screen iframe, then snapshot the
// document with html2canvas and download a PNG. The iframe is needed to
// give the artifact its own document context (CSS resets, fonts, layout
// roots) — capturing a fragment of the host document would inherit our
// app stylesheet and look nothing like the preview.
//
// `width` / `height` default to 1280×800 (a common laptop hero crop) but
// callers should pass the artifact's intended canvas size when known.
// Skills that target a specific medium (e.g. social-post-square at
// 1080×1080) declare their dimensions in SKILL.md frontmatter; the share
// menu reads those and forwards them here.
//
// `scale` controls device-pixel ratio. Default 2 produces ~retina output
// (~2.6 MB for 1280×800); pass 1 if file size matters more than fidelity.
export async function exportAsPng(
  html: string,
  title: string,
  opts?: { width?: number; height?: number; scale?: number; backgroundColor?: string },
): Promise<void> {
  const width = opts?.width ?? 1280;
  const height = opts?.height ?? 800;
  const scale = opts?.scale ?? Math.min(2, window.devicePixelRatio || 1);
  const backgroundColor = opts?.backgroundColor ?? '#ffffff';

  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.left = '-99999px';
  iframe.style.top = '0';
  iframe.style.width = `${width}px`;
  iframe.style.height = `${height}px`;
  iframe.style.border = '0';
  iframe.setAttribute('aria-hidden', 'true');
  // We need same-origin to walk the iframe's document tree, plus scripts
  // for skills that lay out via JS (decks, tab strips, etc.).
  iframe.setAttribute('sandbox', 'allow-same-origin allow-scripts');
  iframe.srcdoc = buildSrcdoc(html);
  document.body.appendChild(iframe);

  try {
    await new Promise<void>((resolve) => {
      let done = false;
      const finish = () => {
        if (done) return;
        done = true;
        resolve();
      };
      iframe.addEventListener('load', finish, { once: true });
      // Safety: never hang the UI if `load` doesn't fire (some skills
      // never resolve their image loads on a hidden iframe).
      setTimeout(finish, 5000);
    });
    // One extra tick so fonts/images settle after `load` fires.
    await new Promise((r) => setTimeout(r, 250));

    const doc = iframe.contentDocument;
    if (!doc) throw new Error('PNG export: iframe document unavailable');

    const html2canvasMod = await import('html2canvas');
    const html2canvas = html2canvasMod.default;
    const canvas = await html2canvas(doc.documentElement, {
      width,
      height,
      windowWidth: width,
      windowHeight: height,
      backgroundColor,
      useCORS: true,
      allowTaint: false,
      scale,
      logging: false,
    });

    const blob: Blob = await new Promise((resolve, reject) => {
      canvas.toBlob((b) => {
        if (b) resolve(b);
        else reject(new Error('PNG export: canvas.toBlob returned null'));
      }, 'image/png');
    });
    triggerDownload(blob, `${safeFilename(title, 'artifact')}.png`);
  } finally {
    iframe.remove();
  }
}
