// Client-side export helpers used by the Share menu in the HTML viewer.
// All four formats run entirely in the browser:
//   - PDF  : open the artifact in a popup window and trigger window.print().
//            The user picks "Save as PDF" from the system print dialog.
//   - PPTX : parse the HTML and emit a real .pptx via pptxgenjs (see ./pptx.ts).
//   - HTML : download the artifact as a single .html file via a Blob URL.
//   - ZIP  : pack the artifact into a stored-mode ZIP (see ./zip.ts).

import { buildSrcdoc } from './srcdoc';
import { buildZip } from './zip';

export { exportAsPptx } from './pptx';

function safeFilename(name: string, fallback: string): string {
  const slug = (name || fallback)
    .replace(/[^\w.\-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return slug || fallback;
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke later — Safari sometimes hasn't finished reading the blob yet
  // when the click handler returns.
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

export function exportAsHtml(html: string, title: string): void {
  const doc = buildSrcdoc(html);
  const blob = new Blob([doc], { type: 'text/html;charset=utf-8' });
  triggerDownload(blob, `${safeFilename(title, 'artifact')}.html`);
}

export function exportAsZip(html: string, title: string): void {
  const doc = buildSrcdoc(html);
  const slug = safeFilename(title, 'artifact');
  const blob = buildZip([
    { path: `${slug}/index.html`, content: doc },
    {
      path: `${slug}/README.md`,
      content: `# ${title || slug}\n\nGenerated by Open Design.\nOpen index.html in a browser to view.\n`,
    },
  ]);
  triggerDownload(blob, `${slug}.zip`);
}

// Open the artifact in a new tab via a Blob URL with a self-printing
// script injected. Going through a Blob URL (rather than `window.open('')`
// + `document.write`) avoids two failure modes we hit before:
//   - `noopener` makes `window.open` return null, leaving an empty popup
//     and triggering a duplicate fallback tab.
//   - Cross-document writes are flaky in some browsers and don't always
//     fire load events the way an inline script tied to the document does.
// The injected script also sets the document title so "Save as PDF" picks
// a sensible default filename.
//
// `deck: true` injects an extra print stylesheet that lays every `.slide`
// section out one-per-page top-to-bottom. The deck framework already ships
// equivalent print rules; this is a safety net for older / partially
// regenerated decks where the framework was stripped — without it,
// horizontal-snap decks print only the visible slide.
export function exportAsPdf(
  html: string,
  title: string,
  opts?: { deck?: boolean },
): void {
  let doc = buildSrcdoc(html);
  // Universal print rules first — they preserve background colors,
  // neutralize fixed/sticky overlays, and set a sane default @page.
  // Without this, dark-themed pages print mostly blank because the
  // browser strips backgrounds by default.
  doc = injectUniversalPrintStylesheet(doc);
  // Deck-specific rules layer on top: they override @page to 1920×1080
  // and force one slide per page with no margins.
  if (opts?.deck) doc = injectDeckPrintStylesheet(doc);
  doc = injectPrintScript(doc, title);
  const blob = new Blob([doc], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (!win) {
    // Popup blocked — at least the tab navigation may have happened above.
    // Nothing else we can do without a fresh user gesture.
  }
  // Revoke later — the loaded document keeps a reference until the tab
  // closes; revoking the URL string only removes the lookup name.
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function injectPrintScript(doc: string, title: string): string {
  const safeTitle = JSON.stringify(title || 'artifact');
  // setTimeout gives stylesheets and images one tick to settle before the
  // print dialog measures the page; without it some print previews come
  // out blank in Chrome.
  const script = `<script>try{document.title=${safeTitle}}catch(e){}window.addEventListener('load',function(){setTimeout(function(){try{window.focus();window.print()}catch(e){}},300)})</script>`;
  if (/<\/head>/i.test(doc)) return doc.replace(/<\/head>/i, `${script}</head>`);
  if (/<\/body>/i.test(doc)) return doc.replace(/<\/body>/i, `${script}</body>`);
  return doc + script;
}

// Universal @media print rules applied to every PDF export. These solve
// the "print preview is mostly blank" problem for non-deck artifacts:
//
//   1. `print-color-adjust: exact` forces the browser to keep author
//      backgrounds and dark themes instead of stripping them for ink savings.
//   2. Common `position: fixed`/`sticky` overlays (sticky headers, modals,
//      cookie banners) are demoted to `static` so they don't repeat on
//      every page or eclipse the actual content.
//   3. `@page { margin: 12mm }` gives readable margins; deck mode resets
//      this to 0 via the deck-specific stylesheet that ships afterward.
//   4. `break-inside: avoid-page` on top-level blocks reduces ugly mid-card
//      page breaks for editorial / dashboard artifacts.
const UNIVERSAL_PRINT_CSS = `
@media print {
  *, *::before, *::after {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    color-adjust: exact !important;
  }
  html, body {
    margin: 0 !important;
    padding: 0 !important;
    overflow: visible !important;
  }
  [style*="position: fixed"], [style*="position:fixed"],
  [style*="position: sticky"], [style*="position:sticky"],
  .fixed, .sticky,
  header[class*="sticky"], header[class*="fixed"],
  nav[class*="sticky"], nav[class*="fixed"] {
    position: static !important;
  }
  .no-print, [data-no-print] { display: none !important; }
  @page { margin: 12mm; }
  img, svg, video { max-width: 100% !important; height: auto; }
  body > *, main, article, section { break-inside: avoid-page; }
}
`;

function injectUniversalPrintStylesheet(doc: string): string {
  const tag = `<style data-print="universal">${UNIVERSAL_PRINT_CSS}</style>`;
  if (/<\/head>/i.test(doc)) return doc.replace(/<\/head>/i, `${tag}</head>`);
  if (/<head[^>]*>/i.test(doc)) return doc.replace(/<head[^>]*>/i, (m) => `${m}${tag}`);
  return tag + doc;
}

// Stitches every .slide into a vertical multi-page PDF: 1920×1080 per page,
// no margins, scroll-snap and horizontal flex disabled. `!important` guards
// override skill-specific styles that pin the deck to `display: flex` /
// `overflow: hidden` for on-screen swiping.
const DECK_PRINT_CSS = `
@media print {
  @page { size: 1920px 1080px; margin: 0; }
  html, body {
    width: 1920px !important;
    height: auto !important;
    overflow: visible !important;
    background: #fff !important;
  }
  body {
    display: block !important;
    scroll-snap-type: none !important;
    transform: none !important;
  }
  .slide, [data-screen-label], section.slide, .deck-slide, .ppt-slide {
    flex: none !important;
    width: 1920px !important;
    height: 1080px !important;
    min-height: 1080px !important;
    max-height: 1080px !important;
    page-break-after: always;
    break-after: page;
    scroll-snap-align: none !important;
    transform: none !important;
    position: relative !important;
    overflow: hidden !important;
  }
  .slide:last-child, [data-screen-label]:last-child { page-break-after: auto; break-after: auto; }
  .deck-counter, .deck-hint, .deck-nav,
  [aria-label="Previous slide"], [aria-label="Next slide"] {
    display: none !important;
  }
}
`;

function injectDeckPrintStylesheet(doc: string): string {
  const tag = `<style data-deck-print="injected">${DECK_PRINT_CSS}</style>`;
  if (/<\/head>/i.test(doc)) return doc.replace(/<\/head>/i, `${tag}</head>`);
  if (/<head[^>]*>/i.test(doc)) return doc.replace(/<head[^>]*>/i, (m) => `${m}${tag}`);
  return tag + doc;
}
